name: Deploy to surge.sh

on:
  push:
    branches: [ master ]

jobs:
  deploy-to-surge-sh:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.*

    - name: Publish .NET Core Project
      run: dotnet publish IncrementalSheep.csproj -c Release -o release --nologo

    - name: Push to surge.sh
      uses: dswistowski/surge-sh-action@v1
      with:
        domain: incremental-sheep.surge.sh
        project: 'release/wwwroot'
        login: ${{ secrets.surge_login }}
        token: ${{ secrets.surge_token }}
